# ZSH Themes
.oh-my-zsh/custom/themes/powerlevel10k:
  type: git-repo
  url: https://github.com/romkatv/powerlevel10k.git
  refreshPeriod: 168h

# Vim Plugins &etc.
.vim/pack/vim-sensible/start/vim-sensible:
  type: archive
  url: https://github.com/tpope/vim-sensible/archive/master.tar.gz
  stripComponents: 1
## File Navigation/Version Control
.vim/pack/scrooloose/start/nerdtree:
  type: archive
  url: https://github.com/scrooloose/nerdtree/archive/master.tar.gz
  stripComponents: 1
.vim/pack/Xuyuanp/start/nerdtree-git-plugin:
  type: archive
  url: https://github.com/Xuyuanp/nerdtree-git-plugin/archive/master.tar.gz
  stripComponents: 1
.vim/pack/tpope/start/vim-fugitive:
  type: archive
  url: https://github.com/tpope/vim-fugitive/archive/master.tar.gz
  stripComponents: 1
## Color Schemes
.vim/pack/morhetz/opt/gruvbox:
  type: archive
  url: https://github.com/morhetz/gruvbox/archive/master.tar.gz
  stripComponents: 1
.vim/pack/tomasr/opt/molokai:
  type: archive
  url: https://github.com/tomasr/molokai/archive/master.tar.gz
  stripComponents: 1
.vim/pack/rakr/opt/vim-one:
  type: archive
  url: https://github.com/rakr/vim-one/archive/master.tar.gz
  stripComponents: 1

# Ranger Plugins
.config/ranger/plugins/ranger_devicons:
  type: archive
  url: https://github.com/alexanderjeurissen/ranger_devicons/archive/main.tar.gz
  stripComponents: 1
